# Generated by Django 4.2.3 on 2023-07-18 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("elevator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="elevator",
            name="direction",
            field=models.CharField(
                choices=[("up", "Up"), ("down", "Down"), ("stop", "Stop")],
                default="stop",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="elevatorrequest",
            name="elevator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="elevator_requests",
                to="elevator.elevator",
            ),
        ),
    ]
