# Generated by Django 4.2.3 on 2023-07-19 18:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elevator", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elevator",
            name="destination_floor",
            field=models.IntegerField(
                blank=True,
                default=None,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="elevatorrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("FINISHED", "FINISHED"),
                    ("QUEUED", "QUEUED"),
                    ("PROCESSING", "PROCESSING"),
                ],
                default="QUEUED",
                max_length=15,
            ),
        ),
    ]
