# Generated by Django 4.2.3 on 2023-07-19 00:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elevator", "0002_elevator_direction_alter_elevatorrequest_elevator"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="elevator",
            name="direction",
        ),
        migrations.AddField(
            model_name="elevatorsystem",
            name="time_elapsed",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
